import withIconWrapper from '~/components/hoc/withIconWrapper';

import Facebook from '~/assets/icons/Facebook-1.svg?react';
import Twitter from '~/assets/icons/Twitter-1.svg?react';
import Discord from '~/assets/icons/Discord.svg?react';
import Telegram from '~/assets/icons/Telegram-1.svg?react';
import Mail from '~/assets/icons/Sms.svg?react';
import Phone from '~/assets/icons/Call.svg?react';
import Location from '~/assets/icons/Location.svg?react';
import Plus from '~/assets/icons/add.svg?react';
import Menu from '~/assets/icons/menu.svg?react';
import Close from '~/assets/icons/clear.svg?react';
import ArrowRight from '~/assets/icons/east.svg?react';
import GiftCard from '~/assets/icons/gift-card.svg?react';
import GiftShape from '~/assets/icons/gift-shape.svg?react';
import HeroShape from '~/assets/icons/shape.svg?react';
import SecurePaymaent from '~/assets/icons/Secure Payments.svg?react';
import OneClick from '~/assets/icons/One click.svg?react';
import InstantDelivery from '~/assets/icons/Instant Delivery.svg?react';
import HiddenCharges from '~/assets/icons/Hidden Charges.svg?react';
import ExpandMore from '~/assets/icons/expand_more.svg?react';
import Binance from '~/assets/icons/binance-logo.svg?react';
import Tron from '~/assets/icons/tron-logo.svg?react';
import WalletFill from '~/assets/icons/wallet-1.svg?react';
import WalletConnect from '~/assets/icons/wallet-connect.svg?react';
import Bitcoin from '~/assets/icons/bitcoin-icon.svg?react';
import Coinbase from '~/assets/icons/coinbase-icon.svg?react';
import Success from '~/assets/icons/success.svg?react';
import Copy from '~/assets/icons/Copy.svg?react';
import FileDownlaod from '~/assets/icons/file_download.svg?react';
import Eye from '~/assets/icons/Eye.svg?react';
import EyeSlash from '~/assets/icons/Eye-slash.svg?react';
import Settings from '~/assets/icons/setting-2.svg?react';
import Person from '~/assets/icons/person_outline.svg?react';
import Logout from '~/assets/icons/logout.svg?react';
import Edit from '~/assets/icons/edit.svg?react';
import TotalIncome from '~/assets/icons/totalIncome.svg?react';
import TotalOrders from '~/assets/icons/totalOrders.svg?react';
import ArrowUpDiagonal from '~/assets/icons/north_east.svg?react';
import Increase from '~/assets/icons/Increase.svg?react';
import ChevronRight from '~/assets/icons/chevron_right.svg?react';
import Delete from '~/assets/icons/delete.svg?react';
import MetaMask from '~/assets/icons/MetaMask-icon-fox.svg?react';
import Failed from '~/assets/icons/Failed.svg?react';
import Phantom from '~/assets/icons/Phantom.svg?react';
import QrCode from '~/assets/icons/qr-code.svg?react';

export const FacebookIcon = withIconWrapper(Facebook);
export const TwitterIcon = withIconWrapper(Twitter);
export const DiscordIcon = withIconWrapper(Discord);
export const TelegramIcon = withIconWrapper(Telegram);
export const MailIcon = withIconWrapper(Mail);
export const PhoneIcon = withIconWrapper(Phone);
export const LocationIcon = withIconWrapper(Location);
export const PlusIcon = withIconWrapper(Plus);
export const MenuIcon = withIconWrapper(Menu);
export const CloseIcon = withIconWrapper(Close);
export const ArrowRightIcon = withIconWrapper(ArrowRight);
export const GiftCardIcon = withIconWrapper(GiftCard);
export const GiftShapeIcon = withIconWrapper(GiftShape);
export const HeroShapeIcon = withIconWrapper(HeroShape);
export const SecurePaymaentIcon = withIconWrapper(SecurePaymaent);
export const OneClickIcon = withIconWrapper(OneClick);
export const InstantDeliveryIcon = withIconWrapper(InstantDelivery);
export const HiddenChargesIcon = withIconWrapper(HiddenCharges);
export const ChevronDown = withIconWrapper(ExpandMore);
export const BinanceIcon = withIconWrapper(Binance);
export const TronIcon = withIconWrapper(Tron);
export const WalletFillIcon = withIconWrapper(WalletFill);
export const WalletConnectIcon = withIconWrapper(WalletConnect);
export const BitcoinIcon = withIconWrapper(Bitcoin);
export const CoinbaseIcon = withIconWrapper(Coinbase);
export const MetaMaskIcon = withIconWrapper(MetaMask);
export const SuccessIcon = withIconWrapper(Success);
export const CopyIcon = withIconWrapper(Copy);
export const DownloadIcon = withIconWrapper(FileDownlaod);
export const EyeIcon = withIconWrapper(Eye);
export const EyeSlashIcon = withIconWrapper(EyeSlash);
export const SettingsIcon = withIconWrapper(Settings);
export const PersonIcon = withIconWrapper(Person);
export const LogoutIcon = withIconWrapper(Logout);
export const EditIcon = withIconWrapper(Edit);
export const TotalIncomeIcon = withIconWrapper(TotalIncome);
export const TotalOrdersIcon = withIconWrapper(TotalOrders);
export const ArrowUpDiagonalIcon = withIconWrapper(ArrowUpDiagonal);
export const IncreaseIcon = withIconWrapper(Increase);
export const ChevronRightIcon = withIconWrapper(ChevronRight);
export const DeleteIcon = withIconWrapper(Delete);
export const FailedIcon = withIconWrapper(Failed);
export const PhantomIcon = withIconWrapper(Phantom);
export const QrCodeIcon = withIconWrapper(QrCode);
